#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="gymshop")]
	public partial class GymShopDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPACKAGE(PACKAGE instance);
    partial void UpdatePACKAGE(PACKAGE instance);
    partial void DeletePACKAGE(PACKAGE instance);
    partial void InsertUSER(USER instance);
    partial void UpdateUSER(USER instance);
    partial void DeleteUSER(USER instance);
    partial void InsertCUSTOMER_SHIP(CUSTOMER_SHIP instance);
    partial void UpdateCUSTOMER_SHIP(CUSTOMER_SHIP instance);
    partial void DeleteCUSTOMER_SHIP(CUSTOMER_SHIP instance);
    partial void InsertROOM(ROOM instance);
    partial void UpdateROOM(ROOM instance);
    partial void DeleteROOM(ROOM instance);
    partial void InsertCUSTOMER(CUSTOMER instance);
    partial void UpdateCUSTOMER(CUSTOMER instance);
    partial void DeleteCUSTOMER(CUSTOMER instance);
    #endregion
		
		public GymShopDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GymShopDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GymShopDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GymShopDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PACKAGE> PACKAGEs
		{
			get
			{
				return this.GetTable<PACKAGE>();
			}
		}
		
		public System.Data.Linq.Table<USER> USERs
		{
			get
			{
				return this.GetTable<USER>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER_SHIP> CUSTOMER_SHIPs
		{
			get
			{
				return this.GetTable<CUSTOMER_SHIP>();
			}
		}
		
		public System.Data.Linq.Table<ROOM> ROOMs
		{
			get
			{
				return this.GetTable<ROOM>();
			}
		}
		
		public System.Data.Linq.Table<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this.GetTable<CUSTOMER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PACKAGES")]
	public partial class PACKAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PACKAGEID;
		
		private string _PACKAGENAME;
		
		private int _DURATIONDAYS;
		
		private decimal _PRICE;
		
		private EntitySet<CUSTOMER_SHIP> _CUSTOMER_SHIPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPACKAGEIDChanging(int value);
    partial void OnPACKAGEIDChanged();
    partial void OnPACKAGENAMEChanging(string value);
    partial void OnPACKAGENAMEChanged();
    partial void OnDURATIONDAYSChanging(int value);
    partial void OnDURATIONDAYSChanged();
    partial void OnPRICEChanging(decimal value);
    partial void OnPRICEChanged();
    #endregion
		
		public PACKAGE()
		{
			this._CUSTOMER_SHIPs = new EntitySet<CUSTOMER_SHIP>(new Action<CUSTOMER_SHIP>(this.attach_CUSTOMER_SHIPs), new Action<CUSTOMER_SHIP>(this.detach_CUSTOMER_SHIPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKAGEID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PACKAGEID
		{
			get
			{
				return this._PACKAGEID;
			}
			set
			{
				if ((this._PACKAGEID != value))
				{
					this.OnPACKAGEIDChanging(value);
					this.SendPropertyChanging();
					this._PACKAGEID = value;
					this.SendPropertyChanged("PACKAGEID");
					this.OnPACKAGEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKAGENAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PACKAGENAME
		{
			get
			{
				return this._PACKAGENAME;
			}
			set
			{
				if ((this._PACKAGENAME != value))
				{
					this.OnPACKAGENAMEChanging(value);
					this.SendPropertyChanging();
					this._PACKAGENAME = value;
					this.SendPropertyChanged("PACKAGENAME");
					this.OnPACKAGENAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURATIONDAYS", DbType="Int NOT NULL")]
		public int DURATIONDAYS
		{
			get
			{
				return this._DURATIONDAYS;
			}
			set
			{
				if ((this._DURATIONDAYS != value))
				{
					this.OnDURATIONDAYSChanging(value);
					this.SendPropertyChanging();
					this._DURATIONDAYS = value;
					this.SendPropertyChanged("DURATIONDAYS");
					this.OnDURATIONDAYSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRICE", DbType="Decimal(18,2) NOT NULL")]
		public decimal PRICE
		{
			get
			{
				return this._PRICE;
			}
			set
			{
				if ((this._PRICE != value))
				{
					this.OnPRICEChanging(value);
					this.SendPropertyChanging();
					this._PRICE = value;
					this.SendPropertyChanged("PRICE");
					this.OnPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PACKAGE_CUSTOMER_SHIP", Storage="_CUSTOMER_SHIPs", ThisKey="PACKAGEID", OtherKey="PACKAGEID")]
		public EntitySet<CUSTOMER_SHIP> CUSTOMER_SHIPs
		{
			get
			{
				return this._CUSTOMER_SHIPs;
			}
			set
			{
				this._CUSTOMER_SHIPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CUSTOMER_SHIPs(CUSTOMER_SHIP entity)
		{
			this.SendPropertyChanging();
			entity.PACKAGE = this;
		}
		
		private void detach_CUSTOMER_SHIPs(CUSTOMER_SHIP entity)
		{
			this.SendPropertyChanging();
			entity.PACKAGE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.USERS")]
	public partial class USER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USERID;
		
		private string _USERNAME;
		
		private string _PASSWORDHASH;
		
		private string _ROLE;
		
		private System.Nullable<bool> _ISACTIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERIDChanging(int value);
    partial void OnUSERIDChanged();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnPASSWORDHASHChanging(string value);
    partial void OnPASSWORDHASHChanged();
    partial void OnROLEChanging(string value);
    partial void OnROLEChanged();
    partial void OnISACTIVEChanging(System.Nullable<bool> value);
    partial void OnISACTIVEChanged();
    #endregion
		
		public USER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int USERID
		{
			get
			{
				return this._USERID;
			}
			set
			{
				if ((this._USERID != value))
				{
					this.OnUSERIDChanging(value);
					this.SendPropertyChanging();
					this._USERID = value;
					this.SendPropertyChanged("USERID");
					this.OnUSERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASSWORDHASH", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PASSWORDHASH
		{
			get
			{
				return this._PASSWORDHASH;
			}
			set
			{
				if ((this._PASSWORDHASH != value))
				{
					this.OnPASSWORDHASHChanging(value);
					this.SendPropertyChanging();
					this._PASSWORDHASH = value;
					this.SendPropertyChanged("PASSWORDHASH");
					this.OnPASSWORDHASHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROLE", DbType="NVarChar(10)")]
		public string ROLE
		{
			get
			{
				return this._ROLE;
			}
			set
			{
				if ((this._ROLE != value))
				{
					this.OnROLEChanging(value);
					this.SendPropertyChanging();
					this._ROLE = value;
					this.SendPropertyChanged("ROLE");
					this.OnROLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISACTIVE", DbType="Bit")]
		public System.Nullable<bool> ISACTIVE
		{
			get
			{
				return this._ISACTIVE;
			}
			set
			{
				if ((this._ISACTIVE != value))
				{
					this.OnISACTIVEChanging(value);
					this.SendPropertyChanging();
					this._ISACTIVE = value;
					this.SendPropertyChanged("ISACTIVE");
					this.OnISACTIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER_SHIPS")]
	public partial class CUSTOMER_SHIP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CUSTOMER_SHIPID;
		
		private string _CUSTOMER_CODE;
		
		private int _PACKAGEID;
		
		private System.DateTime _STARTDATE;
		
		private System.DateTime _ENDDATE;
		
		private decimal _TOTALPRICE;
		
		private System.Nullable<System.DateTime> _CREATEDAT;
		
		private EntityRef<PACKAGE> _PACKAGE;
		
		private EntityRef<CUSTOMER> _CUSTOMER;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUSTOMER_SHIPIDChanging(int value);
    partial void OnCUSTOMER_SHIPIDChanged();
    partial void OnCUSTOMER_CODEChanging(string value);
    partial void OnCUSTOMER_CODEChanged();
    partial void OnPACKAGEIDChanging(int value);
    partial void OnPACKAGEIDChanged();
    partial void OnSTARTDATEChanging(System.DateTime value);
    partial void OnSTARTDATEChanged();
    partial void OnENDDATEChanging(System.DateTime value);
    partial void OnENDDATEChanged();
    partial void OnTOTALPRICEChanging(decimal value);
    partial void OnTOTALPRICEChanged();
    partial void OnCREATEDATChanging(System.Nullable<System.DateTime> value);
    partial void OnCREATEDATChanged();
    #endregion
		
		public CUSTOMER_SHIP()
		{
			this._PACKAGE = default(EntityRef<PACKAGE>);
			this._CUSTOMER = default(EntityRef<CUSTOMER>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_SHIPID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CUSTOMER_SHIPID
		{
			get
			{
				return this._CUSTOMER_SHIPID;
			}
			set
			{
				if ((this._CUSTOMER_SHIPID != value))
				{
					this.OnCUSTOMER_SHIPIDChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_SHIPID = value;
					this.SendPropertyChanged("CUSTOMER_SHIPID");
					this.OnCUSTOMER_SHIPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_CODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_CODE
		{
			get
			{
				return this._CUSTOMER_CODE;
			}
			set
			{
				if ((this._CUSTOMER_CODE != value))
				{
					if (this._CUSTOMER.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCUSTOMER_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_CODE = value;
					this.SendPropertyChanged("CUSTOMER_CODE");
					this.OnCUSTOMER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKAGEID", DbType="Int NOT NULL")]
		public int PACKAGEID
		{
			get
			{
				return this._PACKAGEID;
			}
			set
			{
				if ((this._PACKAGEID != value))
				{
					if (this._PACKAGE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPACKAGEIDChanging(value);
					this.SendPropertyChanging();
					this._PACKAGEID = value;
					this.SendPropertyChanged("PACKAGEID");
					this.OnPACKAGEIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STARTDATE", DbType="DateTime NOT NULL")]
		public System.DateTime STARTDATE
		{
			get
			{
				return this._STARTDATE;
			}
			set
			{
				if ((this._STARTDATE != value))
				{
					this.OnSTARTDATEChanging(value);
					this.SendPropertyChanging();
					this._STARTDATE = value;
					this.SendPropertyChanged("STARTDATE");
					this.OnSTARTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ENDDATE", DbType="DateTime NOT NULL")]
		public System.DateTime ENDDATE
		{
			get
			{
				return this._ENDDATE;
			}
			set
			{
				if ((this._ENDDATE != value))
				{
					this.OnENDDATEChanging(value);
					this.SendPropertyChanging();
					this._ENDDATE = value;
					this.SendPropertyChanged("ENDDATE");
					this.OnENDDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALPRICE", DbType="Decimal(18,2) NOT NULL")]
		public decimal TOTALPRICE
		{
			get
			{
				return this._TOTALPRICE;
			}
			set
			{
				if ((this._TOTALPRICE != value))
				{
					this.OnTOTALPRICEChanging(value);
					this.SendPropertyChanging();
					this._TOTALPRICE = value;
					this.SendPropertyChanged("TOTALPRICE");
					this.OnTOTALPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATEDAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATEDAT
		{
			get
			{
				return this._CREATEDAT;
			}
			set
			{
				if ((this._CREATEDAT != value))
				{
					this.OnCREATEDATChanging(value);
					this.SendPropertyChanging();
					this._CREATEDAT = value;
					this.SendPropertyChanged("CREATEDAT");
					this.OnCREATEDATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PACKAGE_CUSTOMER_SHIP", Storage="_PACKAGE", ThisKey="PACKAGEID", OtherKey="PACKAGEID", IsForeignKey=true)]
		public PACKAGE PACKAGE
		{
			get
			{
				return this._PACKAGE.Entity;
			}
			set
			{
				PACKAGE previousValue = this._PACKAGE.Entity;
				if (((previousValue != value) 
							|| (this._PACKAGE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PACKAGE.Entity = null;
						previousValue.CUSTOMER_SHIPs.Remove(this);
					}
					this._PACKAGE.Entity = value;
					if ((value != null))
					{
						value.CUSTOMER_SHIPs.Add(this);
						this._PACKAGEID = value.PACKAGEID;
					}
					else
					{
						this._PACKAGEID = default(int);
					}
					this.SendPropertyChanged("PACKAGE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_CUSTOMER_SHIP", Storage="_CUSTOMER", ThisKey="CUSTOMER_CODE", OtherKey="CUSTOMER_CODE", IsForeignKey=true)]
		public CUSTOMER CUSTOMER
		{
			get
			{
				return this._CUSTOMER.Entity;
			}
			set
			{
				CUSTOMER previousValue = this._CUSTOMER.Entity;
				if (((previousValue != value) 
							|| (this._CUSTOMER.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CUSTOMER.Entity = null;
						previousValue.CUSTOMER_SHIPs.Remove(this);
					}
					this._CUSTOMER.Entity = value;
					if ((value != null))
					{
						value.CUSTOMER_SHIPs.Add(this);
						this._CUSTOMER_CODE = value.CUSTOMER_CODE;
					}
					else
					{
						this._CUSTOMER_CODE = default(string);
					}
					this.SendPropertyChanged("CUSTOMER");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ROOMS")]
	public partial class ROOM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ROOM_ID;
		
		private string _ROOM_CODE;
		
		private string _ROOM_NAME;
		
		private System.Nullable<int> _CAPACITY;
		
		private string _LOCATION;
		
		private string _STATUS;
		
		private string _NOTE;
		
		private EntitySet<CUSTOMER> _CUSTOMERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnROOM_IDChanging(int value);
    partial void OnROOM_IDChanged();
    partial void OnROOM_CODEChanging(string value);
    partial void OnROOM_CODEChanged();
    partial void OnROOM_NAMEChanging(string value);
    partial void OnROOM_NAMEChanged();
    partial void OnCAPACITYChanging(System.Nullable<int> value);
    partial void OnCAPACITYChanged();
    partial void OnLOCATIONChanging(string value);
    partial void OnLOCATIONChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    #endregion
		
		public ROOM()
		{
			this._CUSTOMERs = new EntitySet<CUSTOMER>(new Action<CUSTOMER>(this.attach_CUSTOMERs), new Action<CUSTOMER>(this.detach_CUSTOMERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ROOM_ID
		{
			get
			{
				return this._ROOM_ID;
			}
			set
			{
				if ((this._ROOM_ID != value))
				{
					this.OnROOM_IDChanging(value);
					this.SendPropertyChanging();
					this._ROOM_ID = value;
					this.SendPropertyChanged("ROOM_ID");
					this.OnROOM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_CODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ROOM_CODE
		{
			get
			{
				return this._ROOM_CODE;
			}
			set
			{
				if ((this._ROOM_CODE != value))
				{
					this.OnROOM_CODEChanging(value);
					this.SendPropertyChanging();
					this._ROOM_CODE = value;
					this.SendPropertyChanged("ROOM_CODE");
					this.OnROOM_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ROOM_NAME
		{
			get
			{
				return this._ROOM_NAME;
			}
			set
			{
				if ((this._ROOM_NAME != value))
				{
					this.OnROOM_NAMEChanging(value);
					this.SendPropertyChanging();
					this._ROOM_NAME = value;
					this.SendPropertyChanged("ROOM_NAME");
					this.OnROOM_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPACITY", DbType="Int")]
		public System.Nullable<int> CAPACITY
		{
			get
			{
				return this._CAPACITY;
			}
			set
			{
				if ((this._CAPACITY != value))
				{
					this.OnCAPACITYChanging(value);
					this.SendPropertyChanging();
					this._CAPACITY = value;
					this.SendPropertyChanged("CAPACITY");
					this.OnCAPACITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCATION", DbType="NVarChar(100)")]
		public string LOCATION
		{
			get
			{
				return this._LOCATION;
			}
			set
			{
				if ((this._LOCATION != value))
				{
					this.OnLOCATIONChanging(value);
					this.SendPropertyChanging();
					this._LOCATION = value;
					this.SendPropertyChanged("LOCATION");
					this.OnLOCATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(20)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROOM_CUSTOMER", Storage="_CUSTOMERs", ThisKey="ROOM_CODE", OtherKey="ROOM_CODE")]
		public EntitySet<CUSTOMER> CUSTOMERs
		{
			get
			{
				return this._CUSTOMERs;
			}
			set
			{
				this._CUSTOMERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CUSTOMERs(CUSTOMER entity)
		{
			this.SendPropertyChanging();
			entity.ROOM = this;
		}
		
		private void detach_CUSTOMERs(CUSTOMER entity)
		{
			this.SendPropertyChanging();
			entity.ROOM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUSTOMER")]
	public partial class CUSTOMER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CUSTOMER_ID;
		
		private string _ROOM_CODE;
		
		private string _CUSTOMER_CODE;
		
		private string _CUSTOMER_NAME;
		
		private string _CUSTOMER_EMAIL;
		
		private string _CUSTOMER_PHONE;
		
		private string _CUSTOMER_CCCD;
		
		private string _CUSTOMER_GENDER;
		
		private string _CUSTOMER_ADDRESS;
		
		private string _CUSTOMER_PHOTOURL;
		
		private System.DateTime _CUSTOMER_EXPIRYDATE;
		
		private string _STATUS;
		
		private string _NOTE;
		
		private System.DateTime _CREATE_DATE;
		
		private string _CREATE_USER;
		
		private string _LAST_UPDATE_USER;
		
		private System.Nullable<System.DateTime> _LAST_UPDATE_DATE;
		
		private EntitySet<CUSTOMER_SHIP> _CUSTOMER_SHIPs;
		
		private EntityRef<ROOM> _ROOM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCUSTOMER_IDChanging(int value);
    partial void OnCUSTOMER_IDChanged();
    partial void OnROOM_CODEChanging(string value);
    partial void OnROOM_CODEChanged();
    partial void OnCUSTOMER_CODEChanging(string value);
    partial void OnCUSTOMER_CODEChanged();
    partial void OnCUSTOMER_NAMEChanging(string value);
    partial void OnCUSTOMER_NAMEChanged();
    partial void OnCUSTOMER_EMAILChanging(string value);
    partial void OnCUSTOMER_EMAILChanged();
    partial void OnCUSTOMER_PHONEChanging(string value);
    partial void OnCUSTOMER_PHONEChanged();
    partial void OnCUSTOMER_CCCDChanging(string value);
    partial void OnCUSTOMER_CCCDChanged();
    partial void OnCUSTOMER_GENDERChanging(string value);
    partial void OnCUSTOMER_GENDERChanged();
    partial void OnCUSTOMER_ADDRESSChanging(string value);
    partial void OnCUSTOMER_ADDRESSChanged();
    partial void OnCUSTOMER_PHOTOURLChanging(string value);
    partial void OnCUSTOMER_PHOTOURLChanged();
    partial void OnCUSTOMER_EXPIRYDATEChanging(System.DateTime value);
    partial void OnCUSTOMER_EXPIRYDATEChanged();
    partial void OnSTATUSChanging(string value);
    partial void OnSTATUSChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    partial void OnCREATE_DATEChanging(System.DateTime value);
    partial void OnCREATE_DATEChanged();
    partial void OnCREATE_USERChanging(string value);
    partial void OnCREATE_USERChanged();
    partial void OnLAST_UPDATE_USERChanging(string value);
    partial void OnLAST_UPDATE_USERChanged();
    partial void OnLAST_UPDATE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnLAST_UPDATE_DATEChanged();
    #endregion
		
		public CUSTOMER()
		{
			this._CUSTOMER_SHIPs = new EntitySet<CUSTOMER_SHIP>(new Action<CUSTOMER_SHIP>(this.attach_CUSTOMER_SHIPs), new Action<CUSTOMER_SHIP>(this.detach_CUSTOMER_SHIPs));
			this._ROOM = default(EntityRef<ROOM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CUSTOMER_ID
		{
			get
			{
				return this._CUSTOMER_ID;
			}
			set
			{
				if ((this._CUSTOMER_ID != value))
				{
					this.OnCUSTOMER_IDChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_ID = value;
					this.SendPropertyChanged("CUSTOMER_ID");
					this.OnCUSTOMER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOM_CODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ROOM_CODE
		{
			get
			{
				return this._ROOM_CODE;
			}
			set
			{
				if ((this._ROOM_CODE != value))
				{
					if (this._ROOM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnROOM_CODEChanging(value);
					this.SendPropertyChanging();
					this._ROOM_CODE = value;
					this.SendPropertyChanged("ROOM_CODE");
					this.OnROOM_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_CODE", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_CODE
		{
			get
			{
				return this._CUSTOMER_CODE;
			}
			set
			{
				if ((this._CUSTOMER_CODE != value))
				{
					this.OnCUSTOMER_CODEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_CODE = value;
					this.SendPropertyChanged("CUSTOMER_CODE");
					this.OnCUSTOMER_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_NAME
		{
			get
			{
				return this._CUSTOMER_NAME;
			}
			set
			{
				if ((this._CUSTOMER_NAME != value))
				{
					this.OnCUSTOMER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_NAME = value;
					this.SendPropertyChanged("CUSTOMER_NAME");
					this.OnCUSTOMER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_EMAIL", DbType="NVarChar(30)")]
		public string CUSTOMER_EMAIL
		{
			get
			{
				return this._CUSTOMER_EMAIL;
			}
			set
			{
				if ((this._CUSTOMER_EMAIL != value))
				{
					this.OnCUSTOMER_EMAILChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_EMAIL = value;
					this.SendPropertyChanged("CUSTOMER_EMAIL");
					this.OnCUSTOMER_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_PHONE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_PHONE
		{
			get
			{
				return this._CUSTOMER_PHONE;
			}
			set
			{
				if ((this._CUSTOMER_PHONE != value))
				{
					this.OnCUSTOMER_PHONEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_PHONE = value;
					this.SendPropertyChanged("CUSTOMER_PHONE");
					this.OnCUSTOMER_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_CCCD", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_CCCD
		{
			get
			{
				return this._CUSTOMER_CCCD;
			}
			set
			{
				if ((this._CUSTOMER_CCCD != value))
				{
					this.OnCUSTOMER_CCCDChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_CCCD = value;
					this.SendPropertyChanged("CUSTOMER_CCCD");
					this.OnCUSTOMER_CCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_GENDER", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string CUSTOMER_GENDER
		{
			get
			{
				return this._CUSTOMER_GENDER;
			}
			set
			{
				if ((this._CUSTOMER_GENDER != value))
				{
					this.OnCUSTOMER_GENDERChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_GENDER = value;
					this.SendPropertyChanged("CUSTOMER_GENDER");
					this.OnCUSTOMER_GENDERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_ADDRESS", DbType="NVarChar(50)")]
		public string CUSTOMER_ADDRESS
		{
			get
			{
				return this._CUSTOMER_ADDRESS;
			}
			set
			{
				if ((this._CUSTOMER_ADDRESS != value))
				{
					this.OnCUSTOMER_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_ADDRESS = value;
					this.SendPropertyChanged("CUSTOMER_ADDRESS");
					this.OnCUSTOMER_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_PHOTOURL", DbType="NVarChar(255)")]
		public string CUSTOMER_PHOTOURL
		{
			get
			{
				return this._CUSTOMER_PHOTOURL;
			}
			set
			{
				if ((this._CUSTOMER_PHOTOURL != value))
				{
					this.OnCUSTOMER_PHOTOURLChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_PHOTOURL = value;
					this.SendPropertyChanged("CUSTOMER_PHOTOURL");
					this.OnCUSTOMER_PHOTOURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMER_EXPIRYDATE", DbType="DateTime NOT NULL")]
		public System.DateTime CUSTOMER_EXPIRYDATE
		{
			get
			{
				return this._CUSTOMER_EXPIRYDATE;
			}
			set
			{
				if ((this._CUSTOMER_EXPIRYDATE != value))
				{
					this.OnCUSTOMER_EXPIRYDATEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMER_EXPIRYDATE = value;
					this.SendPropertyChanged("CUSTOMER_EXPIRYDATE");
					this.OnCUSTOMER_EXPIRYDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATUS", DbType="NVarChar(10)")]
		public string STATUS
		{
			get
			{
				return this._STATUS;
			}
			set
			{
				if ((this._STATUS != value))
				{
					this.OnSTATUSChanging(value);
					this.SendPropertyChanging();
					this._STATUS = value;
					this.SendPropertyChanged("STATUS");
					this.OnSTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="NVarChar(100)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime CREATE_DATE
		{
			get
			{
				return this._CREATE_DATE;
			}
			set
			{
				if ((this._CREATE_DATE != value))
				{
					this.OnCREATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._CREATE_DATE = value;
					this.SendPropertyChanged("CREATE_DATE");
					this.OnCREATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATE_USER", DbType="VarChar(20)")]
		public string CREATE_USER
		{
			get
			{
				return this._CREATE_USER;
			}
			set
			{
				if ((this._CREATE_USER != value))
				{
					this.OnCREATE_USERChanging(value);
					this.SendPropertyChanging();
					this._CREATE_USER = value;
					this.SendPropertyChanged("CREATE_USER");
					this.OnCREATE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_USER", DbType="VarChar(20)")]
		public string LAST_UPDATE_USER
		{
			get
			{
				return this._LAST_UPDATE_USER;
			}
			set
			{
				if ((this._LAST_UPDATE_USER != value))
				{
					this.OnLAST_UPDATE_USERChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_USER = value;
					this.SendPropertyChanged("LAST_UPDATE_USER");
					this.OnLAST_UPDATE_USERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LAST_UPDATE_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> LAST_UPDATE_DATE
		{
			get
			{
				return this._LAST_UPDATE_DATE;
			}
			set
			{
				if ((this._LAST_UPDATE_DATE != value))
				{
					this.OnLAST_UPDATE_DATEChanging(value);
					this.SendPropertyChanging();
					this._LAST_UPDATE_DATE = value;
					this.SendPropertyChanged("LAST_UPDATE_DATE");
					this.OnLAST_UPDATE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CUSTOMER_CUSTOMER_SHIP", Storage="_CUSTOMER_SHIPs", ThisKey="CUSTOMER_CODE", OtherKey="CUSTOMER_CODE")]
		public EntitySet<CUSTOMER_SHIP> CUSTOMER_SHIPs
		{
			get
			{
				return this._CUSTOMER_SHIPs;
			}
			set
			{
				this._CUSTOMER_SHIPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ROOM_CUSTOMER", Storage="_ROOM", ThisKey="ROOM_CODE", OtherKey="ROOM_CODE", IsForeignKey=true)]
		public ROOM ROOM
		{
			get
			{
				return this._ROOM.Entity;
			}
			set
			{
				ROOM previousValue = this._ROOM.Entity;
				if (((previousValue != value) 
							|| (this._ROOM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ROOM.Entity = null;
						previousValue.CUSTOMERs.Remove(this);
					}
					this._ROOM.Entity = value;
					if ((value != null))
					{
						value.CUSTOMERs.Add(this);
						this._ROOM_CODE = value.ROOM_CODE;
					}
					else
					{
						this._ROOM_CODE = default(string);
					}
					this.SendPropertyChanged("ROOM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CUSTOMER_SHIPs(CUSTOMER_SHIP entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = this;
		}
		
		private void detach_CUSTOMER_SHIPs(CUSTOMER_SHIP entity)
		{
			this.SendPropertyChanging();
			entity.CUSTOMER = null;
		}
	}
}
#pragma warning restore 1591
